package me.shy.logging;

import java.util.Locale;
import java.util.ResourceBundle;

import org.apache.log4j.Logger;

public class Constants {
	
	public static Logger LOGGER = Logger.getLogger(Logging.class);
	public static String CONFIG_FILE_PATH = System.getProperty("user.dir") + "\\LoggingConfig.xml";
	
	private static ResourceBundle defaultBundle = ResourceBundle.getBundle("logging" , Locale.getDefault()); 
	public static String NOTIFY_TITLE = defaultBundle.getString("notify_title");
	public static String ERROR_TITLE = defaultBundle.getString("error_title");
	public static String PROFILES_FORMAT_ERROR = defaultBundle.getString("profiles_format_error");
	public static String EXPORT_FILE_FAILED = defaultBundle.getString("export_file_fail");
	public static String JAR_FILE = defaultBundle.getString("jar_file");
	public static String TEXT_FILE = defaultBundle.getString("text_file");
	public static String XML_FILE = defaultBundle.getString("xml_file");
	public static String ADD = defaultBundle.getString("add");
	public static String DELETE = defaultBundle.getString("delete");
	public static String NO_SELECTED_BSC = defaultBundle.getString("no_selected_bsc");
	public static String DEL_SELECTED_BSC = defaultBundle.getString("want_del_selected_bsc");
	public static String TOTAL = defaultBundle.getString("total");
	public static String EXIT = defaultBundle.getString("exit");
	public static String EXIT_TASK = defaultBundle.getString("exit_ask");
	public static String EXPORT = defaultBundle.getString("export");
	public static String IMPORT = defaultBundle.getString("import");
	public static String RESTART = defaultBundle.getString("restart");
	public static String OPEN_CONFIG_FILE = defaultBundle.getString("open_config_file");
	public static String CONFIG_FILE_NOT_FOUND = defaultBundle.getString("config_file_not_found");
	public static String OPEN = defaultBundle.getString("open");
	public static String OPEN_LOG_DIR = defaultBundle.getString("open_log_dir");
	public static String LOG_DIR_NO_SET = defaultBundle.getString("log_dir_no_set");
	public static String RUN = defaultBundle.getString("run");
	public static String CONFIG_NOT_COMPLETE = defaultBundle.getString("config_not_complete");
	public static String NO_COMMAND = defaultBundle.getString("no_command");
	public static String NO_TASK = defaultBundle.getString("no_task");
	public static String SELECTED = defaultBundle.getString("selected");
	public static String LOCK = defaultBundle.getString("lock");
	public static String MERGE_LOGS = defaultBundle.getString("merge_logs");
	public static String FINISHED = defaultBundle.getString("finished");
	public static String READY = defaultBundle.getString("ready");
	public static String UNLOCK = defaultBundle.getString("unlock");
	public static String HAS_DONE = defaultBundle.getString("has_done");
	public static String SAVE = defaultBundle.getString("save");
	public static String MAIL_NOT_SUP = defaultBundle.getString("mail_not_sup");
	public static String OK = defaultBundle.getString("ok");
	public static String ABOUT = defaultBundle.getString("about");
	public static String NAME = defaultBundle.getString("name");
	public static String IP = defaultBundle.getString("ip");
	public static String TYPE = defaultBundle.getString("type");
	public static String CANCLE = defaultBundle.getString("cancel");
	public static String NAME_EMPTY = defaultBundle.getString("name_empty");
	public static String IP_EMPTY = defaultBundle.getString("ip_empty");
	public static String EXIST = defaultBundle.getString("exist");
	public static String USERNAME = defaultBundle.getString("username");
	public static String PASSWORD = defaultBundle.getString("password");
	public static String BROWSE = defaultBundle.getString("browse");
	public static String SINGLE_LOG = defaultBundle.getString("single_log");
	public static String OTHER = defaultBundle.getString("other");
	public static String STOP = defaultBundle.getString("stop");
	public static String THREAD_NUM = defaultBundle.getString("thread_number");
	public static String SHOW_PASSWD = defaultBundle.getString("show_passwd");
	public static String CONFIG = defaultBundle.getString("config");
	public static String FILE = defaultBundle.getString("file");
	public static String SETTING = defaultBundle.getString("setting");
	public static String HELP = defaultBundle.getString("help");
	public static String OPEN_FILE = defaultBundle.getString("open_file");
	public static String SAVE_FILE = defaultBundle.getString("save_file");
	public static String IMPORT_FILE = defaultBundle.getString("import_file");
	public static String EXPORT_FILE = defaultBundle.getString("export_file");
	public static String EXIT_FILE = defaultBundle.getString("exit_file");
	public static String SELECT = defaultBundle.getString("select");
	public static String UNSELECT = defaultBundle.getString("unselect");
	public static String SELECT_ALL = defaultBundle.getString("select_all");
	public static String SELECT_ZERO = defaultBundle.getString("select_zero");
	public static String CLEAR = defaultBundle.getString("clear");
	public static String COPY = defaultBundle.getString("copy");
	public static String PAST = defaultBundle.getString("past");
	public static String CUT = defaultBundle.getString("cut");
	public static String RUNNING = defaultBundle.getString("running");
	public static String COMMAND = defaultBundle.getString("command");
	public static String IP_UNREACHABLE = defaultBundle.getString("ip_unreachable");
	public static String SOCKET_ERROR = defaultBundle.getString("socket_error");
	public static String IO_ERROR = defaultBundle.getString("io_error");
	public static String ROUTER_AUTHEN_FAILED = defaultBundle.getString("router_authentication_failed");
	public static String CONNECT_FAILED = defaultBundle.getString("connect_failed");
	public static String LOGIN_FAILED = defaultBundle.getString("login_failed");
	public static String CMD_EXE_FAILED = defaultBundle.getString("command_exe_failed");
	public static String CONNECT = defaultBundle.getString("connect");
	public static String DISCONNECT = defaultBundle.getString("disconnect");
}
